import type { Opportunity } from "./types";

export const demoOpportunities: Opportunity[] = [
  {id:"demo-001",title:"Médico Psiquiatra",organization:"Prefeitura Municipal — demonstração",city:"Maceió",state:"AL",specialty:"Psiquiatria",salary:12800,workload:"20h",vacancies:"2 + CR",deadline:"2026-10-18",status:"open",modality:"Concurso",officialUrl:null,sourceName:"Dado demonstrativo",sourceType:"demo",updatedAt:"2026-09-26",fingerprint:"demo-001"},
  {id:"demo-002",title:"Médico ESF",organization:"Secretaria Municipal de Saúde — demonstração",city:"Arapiraca",state:"AL",specialty:"Medicina de Família",salary:15400,workload:"40h",vacancies:"4",deadline:"2026-10-22",status:"open",modality:"Processo seletivo",officialUrl:null,sourceName:"Dado demonstrativo",sourceType:"demo",updatedAt:"2026-09-26",fingerprint:"demo-002"},
  {id:"demo-003",title:"Médico Clínico",organization:"Hospital Público — demonstração",city:"Recife",state:"PE",specialty:"Clínica Médica",salary:11800,workload:"24h",vacancies:"3",deadline:"2026-10-30",status:"open",modality:"Concurso",officialUrl:null,sourceName:"Dado demonstrativo",sourceType:"demo",updatedAt:"2026-09-26",fingerprint:"demo-003"},
  {id:"demo-004",title:"Médico Geriatra",organization:"Autarquia Municipal — demonstração",city:"Florianópolis",state:"SC",specialty:"Geriatria",salary:9800,workload:"20h",vacancies:"1",deadline:"2026-11-08",status:"upcoming",modality:"Concurso",officialUrl:null,sourceName:"Dado demonstrativo",sourceType:"demo",updatedAt:"2026-09-26",fingerprint:"demo-004"},
  {id:"demo-005",title:"Médico do Trabalho",organization:"Empresa Pública — demonstração",city:"São Paulo",state:"SP",specialty:"Medicina do Trabalho",salary:17600,workload:"30h",vacancies:"CR",deadline:"2026-11-12",status:"open",modality:"Concurso",officialUrl:null,sourceName:"Dado demonstrativo",sourceType:"demo",updatedAt:"2026-09-26",fingerprint:"demo-005"},
  {id:"demo-006",title:"Médico Clínico Geral",organization:"Prefeitura Municipal — demonstração",city:"Aracaju",state:"SE",specialty:"Clínica Médica",salary:8600,workload:"20h",vacancies:"2",deadline:"2026-11-15",status:"upcoming",modality:"Processo seletivo",officialUrl:null,sourceName:"Dado demonstrativo",sourceType:"demo",updatedAt:"2026-09-26",fingerprint:"demo-006"}
];
